blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & discussions
    url: https://github.com/n-ramos/celebrimbor/discussions
    about: Pour les questions d'usage, idées et discussions ouvertes.
